### ISSUE TITLE
how to use with ESP-HOME

### ISSUE THREAD

**Issue by gparra99** [mocacinno/rp2040_with_esp8285#3]
Nice and detailed tutorial, by the way. I have followed step 1 perfectly, both rp2040 and esp8285 fw were updated... 

But my question is: I would like to use my pico w with esp-home. Is that possible?

If the Pico W is not a fake one, the procedure should be:

1 - Generate the yaml file
2 - Download it manually to a uf2 file
3 - Connect the pico w to the computer, holding the bootseg button

And that´s it..it should work..but it doesn't because of this 3rd party wifi chip.

Any tips?

thank you in advance.

yaml file:
```
esphome:
  name: picow01
  friendly_name: PicoW01

rp2040:
  board: rpipicow

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "7UmizN6+BiGrx48tQ0zLcW6Lm1b/FpkxG3VaEMnIfsY="

ota:
  - platform: esphome
    password: "3240c2ea8777ed5107b2fa71594d0d65"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Picow01 Fallback Hotspot"
    password: "PDnY6PkqurJf"
    

```
